import { Syne } from "next/font/google";
import "./globals.scss";
import Header from "./sections/Header";
import NavMobile from "./sections/NavMobile";

const syne = Syne({ subsets: ["latin"] });

export const metadata = {
  title: "Trote Solidário UFV | 2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={syne.className}>
        <Header></Header>
        <NavMobile></NavMobile>
        {children}
        </body>
    </html>
  );
}
